name: Deploy Website with Secure Token

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Inject Secret into Environment
        run: |
          echo "PARTICLE_ACCESS_TOKEN=${{ secrets.PARTICLE_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Create env.json File
        run: |
          mkdir -p public  # Ensure public directory exists
          echo '{ "VITE_PARTICLE_ACCESS_TOKEN": "${{ secrets.PARTICLE_ACCESS_TOKEN }}" }' > public/env.json

