name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate env.json
      run: |
        echo '{ "VITE_PARTICLE_ACCESS_TOKEN": "${{ secrets.PARTICLE_AUTH_TOKEN }}" }' > env.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # This should be the directory you want to deploy
        destination_dir: draw  # This specifies the subdirectory in the gh-pages branch
